 --- #YAML:1.0
 name: Net-Shoutcast-Admin
 abstract: Fetch information from a Shoutcast streaming audio server
 version: 0.01
 author:
   - David Precious <davidp@preshweb.co.uk>
 license: perl
 distribution_type: module
 requires:
   LWP::UserAgent: 0
   XML::Simple: 0
   URI::Escape 0
   perl: 5.005_03
 build_requires:
   Test::More: 0
 urls:
   license: http://dev.perl.org/licenses/
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: Module::Build version 0.20